# Title         : .taplo.toml
# Author        : Bardia Samiee
# Project       : Dotfiles
# License       : MIT
# Path          : home/configs/formatting/.taplo.toml
# ---------------------------------------
# TOML formatter and linter configuration

# --- Formatting Configuration ---------------------------------------------
[formatting]
indent_string = "    "
column_width = 120
array_auto_expand = true
array_auto_collapse = false
array_trailing_comma = true
inline_table_expand = false
compact_inline_tables = false
compact_arrays = true
align_comments = false
align_entries = false
compact_entries = false
reorder_keys = false
allowed_blank_lines = 1
trailing_newline = true
crlf = false

[schema]
enabled = true
catalogs = ["https://www.schemastore.org/api/json/catalog.json"]

[[rule]]
include = ["**/Cargo.toml"]
formatting.reorder_keys = true

[[rule]]
include = ["**/pyproject.toml"]
formatting.reorder_keys = false
