# Title         : cargo-deny.toml
# Author        : Bardia Samiee
# Project       : Dotfiles
# License       : MIT
# Path          : home/configs/languages/cargo-deny.toml
# ---------------------------------------
# Cargo dependency auditing configuration

# --- Graph Configuration ---------------------------------------------------
[graph]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
]
all-features = true
no-default-features = false

# --- Security Advisories ---------------------------------------------------
[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = []

[advisories.db-urls]
# Default: https://github.com/RustSec/advisory-db

# --- Dependency Bans -------------------------------------------------------
[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

deny = [
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
    { crate = "libsqlite3-sys", use-instead = "rusqlite" },
]

skip = []
skip-tree = []

# --- License Compliance ----------------------------------------------------
[licenses]
unlicensed = "deny"
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "MPL-2.0",
]

deny = [
    "GPL-3.0",
    "AGPL-3.0",
    "LGPL-3.0",
]

exceptions = []

# --- Source Repository Verification ----------------------------------------
[sources]
unknown-registry = "warn"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []