# Title         : clippy-lints.toml
# Author        : Bardia Samiee
# Project       : Dotfiles
# License       : MIT
# Path          : home/configs/languages/clippy-lints.toml
# ---------------------------------------
# Global Clippy lints configuration for all Rust projects

# --- Workspace Configuration -----------------------------------------------
# For workspace: [workspace.lints.clippy] in workspace Cargo.toml
# For crate: [lints] workspace = true

# --- Single Crate Configuration --------------------------------------------
[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }

module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"

unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
missing_debug_implementations = "warn"
missing_copy_implementations = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
rust_2018_idioms = "warn"
